# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "97a00dce8ef910c604664315987f9599"
application_url = "https://patrick-exposed-rough-responsibilities.trycloudflare.com"
embedded = true
name = "sennheiser warranty app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_all_orders,write_orders,read_customers,read_products,write_draft_orders"

[webhooks]
api_version = "2026-07"

[events]
api_version = "unstable"

[[events.subscription]]
handle = "product-updates"
topic = "Product"
actions = ["create", "update", "delete"]
uri = "/events/products"

[auth]
redirect_urls = [
  "https://patrick-exposed-rough-responsibilities.trycloudflare.com/api/auth"
]

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://patrick-exposed-rough-responsibilities.trycloudflare.com/tws-warranty"
prefix = "apps"
subpath = "warranty"