# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "97a00dce8ef910c604664315987f9599"
application_url = "https://nearly-fishing-between-crest.trycloudflare.com"
embedded = true
name = "sennheiser warranty app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_customers,read_products,write_draft_orders"

[webhooks]
api_version = "2026-07"

[auth]
redirect_urls = [ "https://nearly-fishing-between-crest.trycloudflare.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://nearly-fishing-between-crest.trycloudflare.com/tws-warranty"
prefix = "apps"
subpath = "warranty"
