# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "97a00dce8ef910c604664315987f9599"
application_url = "https://firmware-sewing-switched-dash.trycloudflare.com"
embedded = true
name = "sennheiser warranty app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[webhooks]
api_version = "2026-07"

[auth]
redirect_urls = [ "https://firmware-sewing-switched-dash.trycloudflare.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
